SET search_path TO lbaw2454;
-- Step 1: Insert Images
INSERT INTO Image (path) VALUES
('images/user1.jpg'),
('images/user2.jpg'),
('images/user3.jpg'),
('images/user4.jpg'),
('images/user5.jpg'),
('images/user6.jpg'),
('images/user7.jpg'),
('images/user8.jpg'),
('images/user9.jpg'),
('images/user10.jpg'),
('images/user11.jpg'),
('images/user12.jpg'),
('images/user13.jpg'),
('images/user14.jpg'),
('images/user15.jpg'),
('images/user16.jpg'),
('images/user17.jpg'),
('images/user18.jpg'),
('images/user19.jpg'),
('images/user20.jpg'),
('images/user21.jpg'),
('images/user22.jpg'),
('images/user23.jpg'),
('images/user24.jpg'),
('images/user25.jpg'),
('images/user26.jpg'),
('images/user27.jpg'),
('images/user28.jpg'),
('images/user29.jpg'),
('images/user30.jpg'),
('images/user31.jpg'),
('images/user32.jpg'),
('images/user33.jpg'),
('images/user34.jpg'),
('images/user35.jpg'),
('images/user36.jpg'),
('images/user37.jpg'),
('images/user38.jpg'),
('images/user39.jpg'),
('images/user40.jpg'),
('images/user41.jpg'),
('images/user42.jpg'),
('images/user43.jpg'),
('images/user44.jpg'),
('images/user45.jpg'),
('images/user46.jpg'),
('images/user47.jpg'),
('images/user48.jpg'),
('images/user49.jpg'),
('images/user50.jpg');


-- Step 2: Insert Users into AuthenticatedUser
INSERT INTO AuthenticatedUser (name, username, email, password, birthDate, description, imageID)
VALUES
('Anonymous', 'Anonymous', 'anonymous@example.com', 'anonymous123', '1000-01-01', 'Anonymous.', 1),
('Bob Johnson', 'bob', 'bob@example.com', 'password123', '1988-02-02', 'Loves to share news.', 2),
('Charlie Brown', 'charlie', 'charlie@example.com', 'password123', '1992-03-03', 'Tech enthusiast.', 3),
('Diana Prince', 'diana', 'diana@example.com', 'password123', '1985-04-04', 'Avid reader and commenter.', 4),
('Edward Elric', 'edward', 'edward@example.com', 'password123', '1994-05-05', 'Anime and manga lover.', 5),
('Fiona Gallagher', 'fiona', 'fiona@example.com', 'password123', '1991-06-06', 'Loves traveling and photography.', 6),
('George Martin', 'george', 'george@example.com', 'password123', '1975-07-07', 'Fantasy writer and fan.', 7),
('Hannah Montana', 'hannah', 'hannah@example.com', 'password123', '1998-08-08', 'Pop culture enthusiast.', 8),
('Ian Malcolm', 'ian', 'ian@example.com', 'password123', '1980-09-09', 'Dinosaur expert and scientist.', 9),
('Jack Sparrow', 'jack', 'jack@example.com', 'password123', '1980-10-10', 'Pirate captain and adventurer.', 10),
('Katherine Pierce', 'katherine', 'katherine@example.com', 'password123', '1993-11-11', 'Mystery novel lover.', 11),
('Liam Neeson', 'liam', 'liam@example.com', 'password123', '1982-12-12', 'Film and theater enthusiast.', 12),
('Monica Geller', 'monica', 'monica@example.com', 'password123', '1980-01-13', 'Chef and cleanliness freak.', 13),
('Nina Williams', 'nina', 'nina@example.com', 'password123', '1979-02-14', 'Martial artist and game developer.', 14),
('Oscar Wilde', 'oscar', 'oscar@example.com', 'password123', '1854-03-15', 'Famous playwright and poet.', 15),
('Penny Lane', 'penny', 'penny@example.com', 'password123', '1992-04-16', 'Music lover and singer.', 16),
('Quentin Tarantino', 'quentin', 'quentin@example.com', 'password123', '1963-05-17', 'Director and screenwriter.', 17),
('Rachel Green', 'rachel', 'rachel@example.com', 'password123', '1988-06-18', 'Fashion enthusiast.', 18),
('Steve Rogers', 'steve', 'steve@example.com', 'password123', '1922-07-19', 'Super soldier and leader.', 19),
('Tony Stark', 'tony', 'tony@example.com', 'password123', '1970-08-20', 'Inventor and philanthropist.', 20),
('Ursula K. Le Guin', 'ursula', 'ursula@example.com', 'password123', '1929-09-21', 'Renowned fantasy author.', 21),
('Victor Frankenstein', 'victor', 'victor@example.com', 'password123', '1794-10-22', 'Scientist and creator.', 22),
('Will Turner', 'will', 'will@example.com', 'password123', '1985-11-23', 'Blacksmith and pirate.', 23),
('Xena Warrior', 'xena', 'xena@example.com', 'password123', '1985-12-24', 'Warrior princess and leader.', 24),
('Yoda', 'yoda', 'yoda@example.com', 'password123', '896-01-25', 'Jedi Master and wise mentor.', 25),
('Zorro', 'zorro', 'zorro@example.com', 'password123', '1840-02-26', 'Masked hero and protector.', 26),
('Albus Dumbledore', 'albus', 'albus@example.com', 'password123', '1881-03-27', 'Headmaster of Hogwarts.', 27),
('Bella Swan', 'bella', 'bella@example.com', 'password123', '1987-04-28', 'Vampire and werewolf enthusiast.', 28),
('Clark Kent', 'clark', 'clark@example.com', 'password123', '1985-05-29', 'Journalist and superhero.', 29),
('Darth Vader', 'darth', 'darth@example.com', 'password123', '1941-06-30', 'Sith Lord and father figure.', 30),
('Elliot Alderson', 'elliot', 'elliot@example.com', 'password123', '1992-07-31', 'Cybersecurity engineer.', 31),
('Frodo Baggins', 'frodo', 'frodo@example.com', 'password123', '1968-08-01', 'Ring bearer and adventurer.', 32),
('Gandalf the Grey', 'gandalf', 'gandalf@example.com', 'password123', '1000-09-02', 'Wielder of magic and wisdom.', 33),
('Homer Simpson', 'homer', 'homer@example.com', 'password123', '1956-10-03', 'Loves donuts and family.', 34),
('Icarus', 'icarus', 'icarus@example.com', 'password123', '2000-11-04', 'Aspiring inventor and dreamer.', 35),
('Jules Winnfield', 'jules', 'jules@example.com', 'password123', '1971-12-05', 'Professional hitman with a passion.', 36),
('Katniss Everdeen', 'katniss', 'katniss@example.com', 'password123', '1990-01-06', 'Revolutionary and survivor.', 37),
('Lara Croft', 'lara', 'lara@example.com', 'password123', '1975-02-07', 'Adventurer and archaeologist.', 38),
('Marty McFly', 'marty', 'marty@example.com', 'password123', '1968-03-08', 'Time traveler and teenager.', 39),
('Nancy Drew', 'nancy', 'nancy@example.com', 'password123', '1980-04-09', 'Famous detective and sleuth.', 40),
('Oliver Twist', 'oliver', 'oliver@example.com', 'password123', '1837-05-10', 'Orphan and survivor.', 41),
('Pikachu', 'pikachu', 'pikachu@example.com', 'password123', '1996-06-11', 'Electric mouse and companion.', 42),
('Quasimodo', 'quasimodo', 'quasimodo@example.com', 'password123', '1460-07-12', 'Bell-ringer and misunderstood.', 43),
('R2-D2', 'r2d2', 'r2d2@example.com', 'password123', '1932-08-13', 'Astromech droid and hero.', 44),
('SpongeBob SquarePants', 'spongebob', 'spongebob@example.com', 'password123', '1986-09-14', 'Underwater fry cook and optimist.', 45),
('Thor Odinson', 'thor', 'thor@example.com', 'password123', '1965-10-15', 'God of thunder and hero.', 46),
('Ultron', 'ultron', 'ultron@example.com', 'password123', '2015-11-16', 'A.I. villain with a complex.', 47),
('Violet Parr', 'violet', 'violet@example.com', 'password123', '2000-12-17', 'Superhero with force fields.', 48),
('Wolverine', 'wolverine', 'wolverine@example.com', 'password123', '1882-01-18', 'Mutant and fighter.', 49),
('X-Men', 'xmen', 'xmen@example.com', 'password123', '1963-02-19', 'Superhero team with various powers.', 50);

-- Step 3: Insert Communities
INSERT INTO Community (name, description, privacy, imageID) VALUES
('Tech Community', 'A place for tech enthusiasts to share knowledge.', FALSE, 1),
('Book Lovers', 'A community for book lovers.', TRUE, 2),
('Anime Fans', 'Discuss your favorite anime and manga.', FALSE, 3),
('Travel Enthusiasts', 'Share your travel stories and tips.', TRUE, 4),
('Fantasy Writers', 'A place for aspiring fantasy authors.', FALSE, 5),
('Culinary Artists', 'Share recipes and cooking tips.', TRUE, 6),
('Movie Buffs', 'Discuss films and series.', FALSE, 7),
('Fitness Fanatics', 'Share fitness tips and motivation.', TRUE, 8),
('Game Developers', 'A community for game creation discussions.', FALSE, 9),
('Nature Lovers', 'Share your nature photography and stories.', TRUE, 10);

-- Step 4: Insert Posts
INSERT INTO Post (title, content, communityID) VALUES
('The Rise of AI', 'Artificial Intelligence is revolutionizing the world.', 1),
('Must-Read Books of 2024', 'Here are some books you shouldn’t miss this year.', 2),
('Top Anime of the Season', 'Let’s discuss the best anime airing this season.', 3),
('Travel Tips for 2024', 'Best destinations to visit next year.', 4),
('Building a Fantasy World', 'Tips for world-building in fantasy fiction.', 5),
('Cooking Healthy Meals', 'Share your best healthy recipes.', 6),
('Upcoming Movies in 2024', 'What films are you excited about?', 7),
('Staying Fit During Winter', 'Winter workouts to keep you healthy.', 8),
('Game Development Basics', 'How to get started with game development.', 9),
('Wildlife Photography Tips', 'Capture nature beautifully.', 10);

-- Step 5: Insert Comments
INSERT INTO Comment (content, creationDate, authenticatedUserID, postID) VALUES
('Great insights! I totally agree with you.', CURRENT_TIMESTAMP, 1, 1),
('I can’t wait to read these books!', CURRENT_TIMESTAMP, 2, 2),
('Anime has really evolved over the years.', CURRENT_TIMESTAMP, 3, 3),
('Looking forward to discussing more on this!', CURRENT_TIMESTAMP, 1, 3),
('Awesome travel tips!', CURRENT_TIMESTAMP, 4, 4),
('Delicious! I want to try this recipe.', CURRENT_TIMESTAMP, 5, 5),
('So many good movies coming up!', CURRENT_TIMESTAMP, 2, 6),
('Let’s keep each other motivated!', CURRENT_TIMESTAMP, 3, 7),
('Game dev is so much fun!', CURRENT_TIMESTAMP, 4, 8),
('Nature is so beautiful!', CURRENT_TIMESTAMP, 5, 9);

-- Step 6: Insert Votes
-- Each user votes for some posts and comments
INSERT INTO Vote (upvote, authenticatedUserID) VALUES
(TRUE, 1), 
(FALSE, 2), 
(TRUE, 3),
(TRUE, 4),
(FALSE, 5),
(TRUE, 6),
(FALSE, 7),
(TRUE, 8),
(FALSE, 9),
(TRUE, 10),
(TRUE, 11),
(FALSE, 12),
(TRUE, 13),
(FALSE, 14),
(TRUE, 15),
(FALSE, 16),
(TRUE, 17),
(FALSE, 18),
(TRUE, 19),
(FALSE, 20),
(TRUE, 21),
(FALSE, 22),
(TRUE, 23),
(FALSE, 24),
(TRUE, 25),
(FALSE, 26),
(TRUE, 27),
(FALSE, 28),
(TRUE, 29),
(FALSE, 30),
(TRUE, 31),
(FALSE, 32),
(TRUE, 33),
(FALSE, 34),
(TRUE, 35),
(FALSE, 36),
(TRUE, 37),
(FALSE, 38),
(TRUE, 39),
(FALSE, 40),
(TRUE, 41),
(FALSE, 42),
(TRUE, 43),
(FALSE, 44),
(TRUE, 45),
(FALSE, 46),
(TRUE, 47),
(FALSE, 48),
(TRUE, 49),
(FALSE, 50);

-- Step 7: Link Votes to Posts
INSERT INTO PostVote (voteID, postID) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 1),
(7, 2),
(8, 3),
(9, 4),
(10, 5),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(16, 1),
(17, 2),
(18, 3),
(19, 4),
(20, 5),
(21, 1),
(22, 2),
(23, 3),
(24, 4),
(25, 5),
(26, 1),
(27, 2),
(28, 3),
(29, 4),
(30, 5),
(31, 1),
(32, 2),
(33, 3),
(34, 4),
(35, 5),
(36, 1),
(37, 2),
(38, 3),
(39, 4),
(40, 5),
(41, 1),
(42, 2),
(43, 3),
(44, 4),
(45, 5),
(46, 1),
(47, 2),
(48, 3),
(49, 4),
(50, 5);

-- Step 8: Insert Comments Votes
INSERT INTO CommentVote (voteID, commentID) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5);

-- Step 9: Insert Topics
INSERT INTO Topic (postID, reviewDate, status) VALUES
(1, CURRENT_TIMESTAMP, 'PENDING'),
(2, CURRENT_TIMESTAMP, 'ACCEPTED'),
(3, CURRENT_TIMESTAMP, 'REJECTED'),
(4, CURRENT_TIMESTAMP, 'PENDING'),
(5, CURRENT_TIMESTAMP, 'ACCEPTED'),
(6, CURRENT_TIMESTAMP, 'PENDING'),
(7, CURRENT_TIMESTAMP, 'ACCEPTED'),
(8, CURRENT_TIMESTAMP, 'PENDING'),
(9, CURRENT_TIMESTAMP, 'REJECTED'),
(10, CURRENT_TIMESTAMP, 'ACCEPTED');

-- Step 10: Insert News
INSERT INTO News (postID, newsURL) VALUES
(1, 'http://example.com/news1'),
(2, 'http://example.com/news2'),
(3, 'http://example.com/news3'),
(4, 'http://example.com/news4'),
(5, 'http://example.com/news5'),
(6, 'http://example.com/news6'),
(7, 'http://example.com/news7'),
(8, 'http://example.com/news8'),
(9, 'http://example.com/news9'),
(10, 'http://example.com/news10');

-- Step 11: Insert Notifications
INSERT INTO Notification (isRead, authenticatedUserID) VALUES
(FALSE, 1),
(FALSE, 2),
(TRUE, 3),
(FALSE, 4),
(TRUE, 5),
(FALSE, 6),
(TRUE, 7),
(FALSE, 8),
(TRUE, 9),
(FALSE, 10),
(FALSE, 11),
(TRUE, 12),
(FALSE, 13),
(TRUE, 14),
(FALSE, 15),
(TRUE, 16),
(FALSE, 17),
(TRUE, 18),
(FALSE, 19),
(TRUE, 20),
(FALSE, 21),
(TRUE, 22),
(FALSE, 23),
(TRUE, 24),
(FALSE, 25),
(TRUE, 26),
(FALSE, 27),
(TRUE, 28),
(FALSE, 29),
(TRUE, 30),
(FALSE, 31),
(TRUE, 32),
(FALSE, 33),
(TRUE, 34),
(FALSE, 35),
(TRUE, 36),
(FALSE, 37),
(TRUE, 38),
(FALSE, 39),
(TRUE, 40),
(FALSE, 41),
(TRUE, 42),
(FALSE, 43),
(TRUE, 44),
(FALSE, 45),
(TRUE, 46),
(FALSE, 47),
(TRUE, 48),
(FALSE, 49),
(TRUE, 50);

-- Step 12: Insert Follow Notifications
INSERT INTO FollowNotification (notificationID, followerID) VALUES
(1, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 6),
(6, 7),
(7, 8),
(8, 9),
(9, 10),
(10, 1),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(16, 6),
(17, 7),
(18, 8),
(19, 9),
(20, 10);
